services:
  nuxt-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: $DOCKER_HUB_IMAGE
    restart: always
    volumes:
      - ./.docker-mounts/nuxt-app:/app/data
    env_file:
      - .env
    ports:
      - 3000:3000
